// Shared word bank — imported by the page and the server.
// [word, part of speech, definition, example, accepted synonyms]
export const LEVELS = {
  easy: [
    ["generous","adj.","willing to give more money, time or help than is expected.","She was generous with her notes before the exam.",["kind"]],
    ["curious","adj.","eager to know or learn something.","A curious kid asks why about everything.",["inquisitive"]],
    ["ancient","adj.","belonging to the very distant past.","They walked through the ruins of an ancient city.",["old"]],
    ["fragile","adj.","easily broken or damaged.","Pack the glasses carefully; they're fragile.",["delicate","breakable"]],
    ["gloomy","adj.","dark or poorly lit, often in a way that feels sad.","A gloomy Monday morning.",["dark","dismal"]],
    ["rapid","adj.","happening in a short time or at great speed.","The city saw rapid growth.",["fast","quick"]],
    ["vast","adj.","extremely large in area or amount.","A vast desert stretched ahead.",["huge","enormous"]],
    ["humble","adj.","not proud; not thinking you are better than others.","He stayed humble after the win.",["modest"]],
    ["eager","adj.","wanting very much to do or have something.","She was eager to start.",["keen"]],
    ["predict","v.","to say what will happen in the future.","Nobody can predict the market.",["forecast"]],
    ["shallow","adj.","not deep.","The kids played in the shallow end.",[]],
    ["reluctant","adj.","unwilling and hesitant.","He was reluctant to speak first.",["unwilling","hesitant"]],
    ["polite","adj.","having good manners and respect for others.","A polite reply, if a little stiff.",["courteous"]],
    ["anxious","adj.","worried or nervous about something uncertain.","She felt anxious before the interview.",["nervous","worried"]],
    ["abundant","adj.","existing in large quantities; more than enough.","Fruit is abundant in summer.",["plentiful"]],
    ["ignore","v.","to deliberately pay no attention to.","He chose to ignore the notification.",[]],
    ["rescue","v.","to save someone from danger.","The crew rescued two hikers.",["save"]],
    ["vivid","adj.","producing strong, clear images in the mind; very bright.","A vivid dream.",["bright"]],
    ["stubborn","adj.","refusing to change your mind.","A stubborn stain, and a stubborn owner.",["obstinate"]],
    ["borrow","v.","to take something with the promise to return it.","Can I borrow your charger?",[]],
  ],
  medium: [
    ["ephemeral","adj.","lasting for a very short time.","Most of what trends today is ephemeral.",["fleeting","transient"]],
    ["esoteric","adj.","understood by only a small group with specialised knowledge.","The talk drifted into esoteric compiler trivia.",["obscure"]],
    ["obfuscate","v.","to make something unclear or harder to understand.","The memo seemed written to obfuscate.",[]],
    ["prosaic","adj.","lacking imagination; ordinary.","The explanation turned out to be prosaic.",["mundane"]],
    ["ubiquitous","adj.","present, appearing, or found everywhere.","Screens are now ubiquitous.",["omnipresent"]],
    ["capricious","adj.","given to sudden, unaccountable changes of mood or behaviour.","The weather here is capricious.",["fickle"]],
    ["fastidious","adj.","very attentive to accuracy and detail.","A fastidious editor catches everything.",["meticulous"]],
    ["pragmatic","adj.","dealing with things sensibly and realistically.","We took the pragmatic option.",["practical"]],
    ["ameliorate","v.","to make something bad or unsatisfactory better.","Small changes can ameliorate the problem.",["improve"]],
    ["cogent","adj.","clear, logical, and convincing.","She made a cogent case for waiting.",["compelling"]],
    ["diffident","adj.","modest or shy because of a lack of self-confidence.","A diffident speaker with sharp ideas.",["timid"]],
    ["insipid","adj.","lacking flavour, interest, or vigour.","An insipid sequel.",["bland"]],
    ["verbose","adj.","using more words than are needed.","The first draft was verbose.",["wordy"]],
    ["zealous","adj.","showing great energy in pursuit of a cause.","A zealous volunteer.",["fervent"]],
    ["candid","adj.","truthful and straightforward; frank.","Thanks for the candid feedback.",["frank"]],
    ["meticulous","adj.","showing great attention to detail; very careful.","Meticulous notes saved the project.",["fastidious"]],
    ["resilient","adj.","able to recover quickly from difficult conditions.","A resilient system degrades gracefully.",[]],
    ["ambiguous","adj.","open to more than one interpretation.","The instructions were ambiguous.",["vague"]],
    ["benevolent","adj.","well meaning and kindly.","A benevolent, slightly nosy landlord.",["kind"]],
    ["tenacious","adj.","holding firmly to something; persistent.","A tenacious debugger.",["persistent"]],
  ],
  hard: [
    ["laconic","adj.","using very few words.","His laconic reply was a single nod.",["terse"]],
    ["obdurate","adj.","stubbornly refusing to change one's opinion or course of action.","The committee remained obdurate despite the evidence.",[]],
    ["perfunctory","adj.","carried out with minimal effort or reflection.","She gave the report a perfunctory glance.",["cursory"]],
    ["sanguine","adj.","optimistic, especially in a difficult situation.","He was oddly sanguine about the deadline.",[]],
    ["pellucid","adj.","translucently clear; easy to understand.","Her prose is pellucid, even on hard topics.",["lucid"]],
    ["recalcitrant","adj.","having an uncooperative attitude toward authority.","A recalcitrant printer is a universal constant.",["refractory"]],
    ["equanimity","n.","calmness and composure, especially under pressure.","She received the news with equanimity.",["composure"]],
    ["magnanimous","adj.","generous or forgiving, especially toward a rival.","He was magnanimous in victory.",[]],
    ["garrulous","adj.","excessively talkative, especially about trivial matters.","A garrulous neighbour kept us at the gate.",["loquacious"]],
    ["mendacious","adj.","not telling the truth; lying.","The ad was misleading, if not outright mendacious.",[]],
    ["intransigent","adj.","unwilling to change one's views or to agree.","Both sides stayed intransigent.",["uncompromising"]],
    ["lugubrious","adj.","looking or sounding sad and dismal.","The cello played something lugubrious.",["mournful"]],
    ["quotidian","adj.","of or occurring every day; mundane.","The quotidian work of keeping things running.",[]],
    ["sycophant","n.","a person who flatters someone powerful to gain advantage.","The CEO was surrounded by sycophants.",[]],
    ["torpid","adj.","mentally or physically inactive; sluggish.","A torpid afternoon after lunch.",["lethargic"]],
    ["alacrity","n.","brisk and cheerful readiness.","She accepted the offer with alacrity.",[]],
    ["obsequious","adj.","excessively eager to please or obey.","An obsequious waiter hovered nearby.",["servile"]],
    ["perspicacious","adj.","having a ready insight into things; shrewd.","A perspicacious reading of the data.",["astute"]],
    ["truculent","adj.","eager or quick to argue or fight.","A truculent reply-all.",["belligerent"]],
    ["vicissitude","n.","a change of circumstances, typically an unwelcome one.","The vicissitudes of startup life.",[]],
  ],
};
for (const k in LEVELS) LEVELS[k] = LEVELS[k].map(([w, pos, def, ex, alt]) => ({ w, pos, def, ex, alt: alt || [] }));

export const ALL_WORDS = Object.values(LEVELS).flat();
export const findWord = w => ALL_WORDS.find(x => x.w === w);
export const levelOf = w => Object.keys(LEVELS).find(l => LEVELS[l].some(x => x.w === w));
